---
apiVersion: apps/v1
kind: Service
metadata:
  name: amazon-prime-service
  labels:
    app: amazon-prime-app
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: amazon-prime-app
  type: LoadBalancer
---
